name: Publish to TestPyPI

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for committing and pushing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install bump2version and build tools
        run: |
          python -m pip install --upgrade pip
          pip install bump2version build twine

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump patch version
        run: |
          bump2version patch

      - name: Show updated version
        run: grep "version=" setup.py

      - name: Pull latest changes before push
        run: |
          git pull --rebase origin main
          git push

      - name: Build dist files
        run: python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASS }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
