name: Publish to TestPyPI

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Auto-bump patch version in setup.py
        run: |
          sed -i -E "s/version='([0-9]+)\.([0-9]+)\.([0-9]+)'/echo version='\1.\2.$((\3+1))'/ge" setup.py
          echo "Updated version:"
          grep "version=" setup.py

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build dist files
        run: python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASS }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
